const COURSE_ACTIVITIES = [
  {id:1,title:'Control-system detective',source:'Prepare for the hardware and IPO work.',fields:[['system','Choose an everyday control system.'],['input','What information enters it?'],['process','What rule or decision is applied?'],['output','What changes as a result?'],['hardware','Map the final alarm inputs and outputs to their fixed pins.'],['check','What will you check before connecting or uploading?']]},
  {id:2,title:'Getting Flashy laboratory',source:'Source pathway 1–2: Getting Flashy and Even Flashier.',fields:[['prediction','Predict the first LED behaviour before upload.'],['result','Record the actual result.'],['timing','Change one delay value. What changed?'],['two-led-plan','Plan a two-LED sequence with exact timing.'],['fault','Record one verification or upload fault and its correction.'],['evidence','What evidence proves the sequence repeated correctly?']]},
  {id:3,title:'Algorithm and flowchart studio',source:'Plan code before typing it.',fields:[['algorithm','Write the ordered steps for a repeating alert.'],['pseudocode','Rewrite the same logic as pseudocode.'],['condition','State the exact decision question.'],['true-path','What happens when the condition is true?'],['false-path','What happens when it is false?'],['dry-run','Dry-run both paths and record any correction.']]},
  {id:4,title:'POT investigation laboratory',source:'Source pathway 3–5: POT Basics, A Light Dimmer and POT LED Bouncer.',fields:[['low','Lowest observed A5 reading and knob condition.'],['middle','Middle observed A5 reading and knob condition.'],['high','Highest observed A5 reading and knob condition.'],['map','State the measured input and intended output ranges.'],['prediction','Predict three mapped outputs.'],['bouncer','Explain how the LED Bouncer uses changing data.'],['calibration','What did calibration change in your code choice?']]},
  {id:5,title:'LDR night-light investigation',source:'Source pathway 6–7: LDR Basics and LDR Night Light.',fields:[['bright','Record repeated A4 readings in bright conditions.'],['normal','Record repeated A4 readings in normal conditions.'],['covered','Record repeated A4 readings when covered.'],['direction','Does the reading rise or fall as light decreases?'],['threshold','Choose and justify a threshold.'],['trigger','Record the alert test result.'],['recovery','Record what happened when light returned.']]},
  {id:6,title:'Button and toggle laboratory',source:'Source pathway 8–9: Push Button Basics and Get A Toggle On.',fields:[['released','Value read from pin 7 when released.'],['pressed','Value read from pin 7 when pressed.'],['condition','Write the correct pressed-state condition.'],['true-output','List every output in the true branch.'],['false-output','List every output in the false branch.'],['state-trace','Trace the Boolean through two recognised presses.'],['bounce','Record the teacher-directed press-recognition method.']]},
  {id:7,title:'Buzzer and pitch laboratory',source:'Source pathway 10–12: Buzzer Basics, Pitch Changer and Play a Song.',fields:[['tone','Record one tested frequency and perceived pitch.'],['silence','Where does the program call noTone?'],['input-range','State the calibrated A5 range.'],['frequency-range','State the tested mapped frequency range.'],['trace','Trace A5 data to buzzer pitch.'],['sequence','Explain the jobs of the note array, loop and function.'],['class-control','Current classroom sound-testing directions: Teacher to confirm.']]},
  {id:8,title:'Combined-system challenge lab',source:'Source pathway 13–15: Electronic Dice, Buzzing Light Meter and LED Magic Sign.',fields:[['challenge','Choose the combined challenge completed.'],['input','Identify its input subsystem.'],['processing','Identify its processing rules.'],['outputs','Identify every output.'],['array','Explain one array and its valid indexes.'],['iteration','Trace the first and final loop iteration.'],['test-order','Write the subsystem test order.'],['fault','Record one interaction fault and correction.']]},
  {id:9,title:'Final alarm design studio',source:'Source pathway 16: Final Alarm Code.',fields:[['brief','What will the alarm protect and for whom?'],['criteria','Write at least five testable criteria.'],['pin-map','Write the final pin map.'],['ipo','Describe the complete input–process–output flow.'],['pseudocode','Write complete normal and alert pseudocode.'],['code-record','Paste the important code or record the teacher-confirmed file location.'],['test-cases','Write five test cases including boundary and recovery.'],['feedback','Record teacher or peer feedback if authorised.']]},
  {id:10,title:'Testing and evaluation builder',source:'Use project evidence to debug, evaluate and back up.',fields:[['fault','Describe one reproducible fault.'],['hypothesis','State the likely cause.'],['change','Record the one change made.'],['retest','Record the retest result.'],['evaluation','Evaluate the alarm against at least five criteria.'],['improvement','Name three precise improvements.'],['learning','Explain the most useful coding idea learned.'],['backup','Record the code version and folio backup completed.'],['submission','Current submission route: Teacher to confirm.']]}
];
