(() => {
  const list = document.querySelector('[data-activity-list]');
  const key = (activity, field) => `crackthecode:activity:${activity}:${field}`;
  list.innerHTML = COURSE_ACTIVITIES.map(activity => `<details class="card activity-card" id="activity-${activity.id}"><summary><span class="number">${activity.id}</span>${activity.title}</summary><div class="activity-body"><p class="fine">${activity.source}</p><div class="field-grid">${activity.fields.map(([id,label]) => `<div><label for="a${activity.id}-${id}">${label}</label><textarea id="a${activity.id}-${id}" data-activity="${activity.id}" data-field="${id}" placeholder="Record specific evidence…"></textarea><p class="save-status" id="status-a${activity.id}-${id}" aria-live="polite"></p></div>`).join('')}</div><p><a href="modules/module-${String(activity.id).padStart(2,'0')}.html">Return to Module ${activity.id} →</a></p></div></details>`).join('');
  const update = () => { const started=COURSE_ACTIVITIES.filter(a=>a.fields.some(([id])=>(localStorage.getItem(key(a.id,id))||'').trim().length>=20)).length; document.querySelector('[data-activity-progress]').textContent=`${started}/10`; };
  document.querySelectorAll('[data-activity][data-field]').forEach(area => { area.value=localStorage.getItem(key(area.dataset.activity,area.dataset.field))||''; let timer; area.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{localStorage.setItem(key(area.dataset.activity,area.dataset.field),area.value);const status=document.getElementById(`status-${area.id}`);status.textContent='Saved on this device';setTimeout(()=>status.textContent='',1600);update();},250);}); });
  if (location.hash) document.querySelector(location.hash)?.setAttribute('open','');
  document.querySelector('[data-print]').addEventListener('click',()=>window.print()); update();
})();
