(() => {
  const nameKey='crackthecode:student-name'; const name=document.querySelector('[data-student-name]'); name.value=localStorage.getItem(nameKey)||''; name.addEventListener('input',()=>localStorage.setItem(nameKey,name.value));
  const moduleRoot=document.querySelector('[data-module-evidence]');
  moduleRoot.innerHTML=COURSE_MODULES.map(module=>`<article class="card evidence-card"><p class="eyebrow">Module ${module.id}</p><h3>${module.title}</h3>${module.sections.map((section,index)=>`<div class="activity-evidence"><label for="folio-${section.written.id}">${section.written.label}</label><textarea id="folio-${section.written.id}" data-key="crackthecode:${section.written.id}" placeholder="Open Module ${module.id} to use the response guide."></textarea><p><a href="modules/module-${String(module.id).padStart(2,'0')}.html#section-${index+1}">Return to precise theory →</a></p></div>`).join('')}</article>`).join('');
  const activityRoot=document.querySelector('[data-activity-evidence]');
  activityRoot.innerHTML=COURSE_ACTIVITIES.map(activity=>`<article class="card activity-summary-card"><p class="eyebrow">Activity ${activity.id}</p><h3>${activity.title}</h3>${activity.fields.map(([id,label])=>`<div class="activity-evidence"><strong>${label}</strong><p data-activity-value="crackthecode:activity:${activity.id}:${id}">No response saved yet.</p></div>`).join('')}<p><a href="activities.html#activity-${activity.id}">Open activity →</a></p></article>`).join('');
  const refresh=()=>{document.querySelectorAll('[data-key]').forEach(area=>area.value=localStorage.getItem(area.dataset.key)||'');document.querySelectorAll('[data-activity-value]').forEach(node=>node.textContent=localStorage.getItem(node.dataset.activityValue)||'No response saved yet.');};
  document.querySelectorAll('[data-key]').forEach(area=>{let timer;area.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>localStorage.setItem(area.dataset.key,area.value),250);});});
  document.querySelector('[data-backup]').addEventListener('click',()=>{const data={version:1,course:'Crack the Code',exported:new Date().toISOString(),storage:{}};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith('crackthecode:'))data.storage[key]=localStorage.getItem(key);}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`crack-the-code-folio-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href);});
  document.querySelector('[data-restore]').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.course!=='Crack the Code'||!data.storage)throw new Error('wrong file');Object.entries(data.storage).forEach(([key,value])=>{if(key.startsWith('crackthecode:'))localStorage.setItem(key,String(value));});name.value=localStorage.getItem(nameKey)||'';refresh();alert('Crack the Code backup restored on this device.');}catch(_){alert('That file is not a valid Crack the Code backup.');}event.target.value='';});
  document.querySelector('[data-print]').addEventListener('click',()=>window.print()); refresh();
})();
